name: perla_task_app
description: perla task app include auth with management operations for set of text.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_localization: 
  flutter_bloc: 
  equatable: 
  dartz:
  get_it:
  internet_connection_checker:
  http:
  shared_preferences:
  go_router: ^6.5.0
  flutter_screenutil:
  sqflite: 
  path:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/languages/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat.ttf
